name: Build Test

on: [push]

## Does the same stuff as publish
## EXCEPT publishing the artifacts

jobs:
  buildtest:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install
      - name: Fetch files
        run: make

      - name: Generate metafiles
        uses: KageKirin/metagen-gha@v0

      - name: Pack
        run: npm pack
      - name: Verify
        run: |
          ls com.kagekirin.github.sprache*.tgz
          tar tvf com.kagekirin.github.sprache*.tgz

      - name: Store package name in env
        run: echo "package_name=`ls com.kagekirin.github.sprache*.tgz`" >> $GITHUB_ENV
      - name: Verify package_name in env
        run: echo "${{ env.package_name }}"
