# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Manual dispatch package

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

jobs:
  dispatch:
    uses: kagekirin/UnitySprache/.github/workflows/publish.yml@main
    with:
      tag: ${{ github.event.inputs.tag }}
    secrets:
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}
