name: Nightly

on:
  schedule:
    - cron: '0 10 * * *'

jobs:
  nightly:
    uses: kagekirin/UnitySprache/.github/workflows/publish.yml@main
    with:
      tag: nightly
    secrets:
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}
