name: Nightly

on:
  schedule:
    cron: '0 10 * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: ./.github/workflows/publish.yml
        with:
          tag: nightly
