# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Release package (NPM)

on:
  release:
    types: [published, edited]

jobs:
  release:
    uses: kagekirin/UnitySprache/.github/workflows/publish.yml@main
    with:
      tag: ${{ github.ref_name }}
